# All mounts assummes docker-machine is used, since some issues with permisions the mounts are in the vm.
# The VIRTUAL_HOST and VIRTUAL_PORT are for dinghy.

gitlab:
  image: 'gitlab/gitlab-ce:8.6.5-ce.0'
  restart: always
  hostname: 'gitlab.docker'
  environment:
    VIRTUAL_HOST: 'gitlab.docker'
    VIRTUAL_PORT: 80
  ports:
    - '81:80'
    - '444:443'
    - '2222:22'
  volumes:
    - '/var/lib/boot2docker/gitlab/config:/etc/gitlab'
    - '/var/lib/boot2docker/gitlab/logs:/var/log/gitlab'
    - '/var/lib/boot2docker/gitlab/data:/var/opt/gitlab'

jenkins:
  build: 'jenkins'
  restart: always
  environment:
    VIRTUAL_HOST: 'jenkins.docker'
    VIRTUAL_PORT: 8080
  links:
    - gitlab:gitlab.docker
    - sonardb:sonardb.docker
  ports:
    - '82:8080'
  volumes:
    - '/var/lib/boot2docker/jenkins:/var/jenkins_home'

artifactory:
  image: 'npalm/artifactory:4.7.1'
  restart: always
  environment:
    VIRTUAL_HOST: 'artifactory.docker'
    VIRTUAL_PORT: 8081
  ports:
    - '87:8081'
  volumes:
    - '/var/lib/boot2docker/artifactory/data:/artifactory/data'
    - '/var/lib/boot2docker/artifactory/logs:/artifactory/logs'
    - '/var/lib/boot2docker/artifactory/backup:/artifactory/backup'

sonardb:
  image: postgres:9
  restart: always
  environment:
    POSTGRES_USER: 'sonar'
    POSTGRES_PASSWORD: 'secret'
  volumes:
    - /var/lib/boot2docker/sonardb/data:/var/lib/postgresql/data

sonar:
  image: sonarqube:5.4
  restart: always
  environment:
    VIRTUAL_HOST: 'sonar.docker'
    VIRTUAL_PORT: 9000
    SONARQUBE_JDBC_USERNAME: 'sonar'
    SONARQUBE_JDBC_PASSWORD: 'secret'
    SONARQUBE_JDBC_URL: 'jdbc:postgresql://sonardb.docker/sonar'
  links:
    - sonardb:sonardb.docker
    - gitlab:gitlab.docker
  ports:
    - "9000:9000"

gitlabrunner:
  image: 'gitlab/gitlab-runner:latest'
  restart: always
  privileged: true
  environment:
    REGISTRATION_TOKEN: 'erGgqG8NGMMsBxDtSpzn'
    CI_SERVER_URL: 'http://gitlab.docker/ci'
    RUNNER_NAME: 'docker-runner'
    RUNNER_EXECUTOR: 'docker'
    RUNNER_LIMIT: '3'
    DOCKER_IMAGE: 'gitlab/dind:latest'
    DOCKER_PRIVILEGED: 'true'
    RUNNER_TAG_LIST: 'dind'
    DOCKER_VOLUMES: '/var/lib/boot2docker/gitlab/runner/gradle_cache:/gradle:rw'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - .data/config:/etc/gitlab-runner

## Register the runner(s) manually :(
#docker exec -i -t buildenv_gitlabrunner_1 gitlab-runner register -n \
#   --docker-links 'cicd_sonardb_1:sonardb.docker' \
#   --docker-links 'cicd_gitlab_1:gitlab.docker' \
#   --docker-links 'cicd_artifactory_1:artifactory.docker'
